import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

const CASE_SELECT = '*, user_card:user_cards(*, card:pokemon_cards(*))'

export async function GET(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const { searchParams } = req.nextUrl
  const assigned = searchParams.get('assigned') // 'true' | 'false' | null
  const code = searchParams.get('code')         // look up one of YOUR cases by short code

  if (code) {
    const { data, error } = await supabase
      .from('cases')
      .select(CASE_SELECT)
      .eq('user_id', user.id)
      .eq('short_code', code.trim().toUpperCase())
      .maybeSingle()
    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    if (!data) return NextResponse.json({ error: 'Case not found' }, { status: 404 })
    return NextResponse.json(data)
  }

  let query = supabase
    .from('cases')
    .select(CASE_SELECT)
    .eq('user_id', user.id)
    .order('created_at', { ascending: false })

  if (assigned === 'true')  query = query.not('user_card_id', 'is', null)
  if (assigned === 'false') query = query.is('user_card_id', null)

  const { data, error } = await query
  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

export async function POST(req: NextRequest) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })

  const body = await req.json().catch(() => ({}))

  // short_code is generated by the DB default (generate_case_short_code)
  const insert: Record<string, unknown> = { user_id: user.id }
  if (body.user_card_id) insert.user_card_id = body.user_card_id
  if (body.location)     insert.location = body.location
  if (body.notes)        insert.notes = body.notes
  for (const flag of ['is_public','show_value','show_grade','show_notes','show_tags']) {
    if (typeof body[flag] === 'boolean') insert[flag] = body[flag]
  }

  // Optional batch create ("count": up to 24 empty cases for a print run)
  const count = Math.min(Math.max(parseInt(body.count) || 1, 1), 24)
  const rows = Array.from({ length: count }, () => ({ ...insert }))

  const { data, error } = await supabase
    .from('cases')
    .insert(rows)
    .select(CASE_SELECT)

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(count === 1 ? data[0] : data, { status: 201 })
}
